services:
  db:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=filer
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run build && node dist/index.js"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/filer?schema=public
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: